import { Testimonial } from "../types";

export const testimonialsData = [
  {
    id: 1,
    name: "Rasikh Adeel",
    role: "Founder & CEO",
    avatar: "/assets/images/review-author-1.jpg",
    rating: 5,
    text: "Partnering with WISH has brought business continuity to us. We are able to deliver and support our customers more effectively and economically.",
    delay: "animate__delay-2",
  },
  {
    id: 2,
    name: "Rakesh Sharma",
    role: "Designer & CEO",
    avatar: "/assets/images/review-author-2.jpg",
    rating: 5,
    text: "Partnering with WISH has brought business continuity to us. We are able to deliver and support our customers more effectively and economically.",
    delay: "animate__delay-3",
  },
  {
    id: 3,
    name: "Vibhuti Gandhi",
    role: "Founder & CEO",
    avatar: "/assets/images/review-author-3.jpg",
    rating: 4.5,
    text: "We are able to service our customers more effectively through the website and web application developed and delivered by WISH.",
    delay: "animate__delay-4",
  },
  {
    id: 4,
    name: "Subhash Shrivastava",
    role: "Founder & CEO",
    avatar: "/assets/images/review-author-4.jpg",
    rating: 5,
    text: "Partnering with WISH has been a game-changer. Their technical expertise has allowed us to provide effective services to our customers.",
    delay: "animate__delay-5",
  },
  {
    id: 5,
    name: "Samir Ahmed",
    role: "CEO",
    avatar: "/assets/images/review-author-5.jpg",
    rating: 5,
    text: "WISH HRMS caters exactly our HR needs. We are able to capture timesheets and process payrolls in no time, providing an efficient solution.",
    delay: "animate__delay-6",
  },
  {
    id: 6,
    name: "Richard Gesimba",
    role: "Operations Director, Manufacturing",
    avatar: "/assets/images/review-author-6.jpg",
    rating: 5,
    text: "ERPNext revolutionised our production planning and inventory management. We've reduced raw material waste by 35% and improved on-time delivery from 72% to 95% within six months.",
    delay: "animate__delay-7",
  },
  {
    id: 7,
    name: "Ann Geoncy",
    role: "Director, Financial Services",
    avatar: "/assets/images/review-author-7.jpg",
    rating: 5,
    text: "Financial consolidation across 3 branches now takes 2 days instead of 1 week. ERPNext's reporting capabilities give us real-time insights into profitability by region and product line.",
    delay: "animate__delay-8",
  },
  {
    id: 8,
    name: "Anudeep Nellore",
    role: "Project Manager, Retail",
    avatar: "/assets/images/review-author-8.jpg",
    rating: 4.5,
    text: "Managing inventory across 12+ stores and 4 online channels was chaos. ERPNext unified everything. Stockouts are down 60%, and inventory turnover improved by 40%.",
    delay: "animate__delay-9",
  },
];
